kind: Env
apiVersion: v1
metadata:
  name: env
spec:
  containers:
    - name: nginx
      image: nginx
      env:
        - name: course
          value: Devops
        - name: duration
          value: 3 months