kind: Service
apiVersion: v1
metadata:
  name: nginx
spec:
  selector:
    project: expense
    environment: dev
    component: backend
    version: "1.0.0"
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
kind: Pod
apiVersion: v1
metadata:
  name: backend
  labels:
    project: expense
    environment: dev
    component: backend
    version: "1.0.0"
spec:
  containers:
    - name: nginx
      image: nginx

